apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customermanagementapi
    version: "1.0"
  name: customermanagementapi-v1
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi
      version: "1.0"
  template:
    metadata:
      labels:
        app: customermanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/customermanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: customermanagementapi
        ports:
        - containerPort: 5100
        livenessProbe:
            httpGet:
              path: /hc
              port: 5100
            initialDelaySeconds: 20
            periodSeconds: 10
      restartPolicy: Always
  