apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
    version: "1.0"
  name: webapp
  namespace: pitstop
spec:
  replicas: 1
  selector: null
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: webapp
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/webapp:1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 7000
        livenessProbe:
            httpGet:
              path: /hc
              port: 7000
            initialDelaySeconds: 20
            periodSeconds: 10
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: pitstop
spec:
  type: LoadBalancer
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    app: webapp

---
